In [1]:
import torch

In [2]:
from torch.autograd import Variable

In [25]:
import  torch.nn as nn
import torch.nn.functional as F

In [6]:
x = Variable(torch.ones(2,2),requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [7]:
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
None
None


In [8]:
y = x+2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [9]:
print(y.grad_fn)

In [10]:
z = y * y *3
out = z.mean()
print(z,out)


tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [17]:
# out.backward()
print(x.grad)
# dout / dx

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [22]:
x = Variable(torch.ones((2,2)),requires_grad = True)
y = x + 2



In [23]:
y.backward(torch.ones(2,2),retain_graph = True)
print(x.grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [24]:
gradient = torch.randn(2, 2)

y.backward(gradient=gradient)
print(x.grad)
torch.cat()

tensor([[ 2.3593, -0.1669],
        [ 1.6160,  1.7519]])


In [31]:
class RNN(nn.Module):
    def __init__(self,data_size, hidden_size, output_size):
        super(RNN,self).__init__()
        self.hidden_size = hidden_size
        input_size = data_size + hidden_size
        
        self.i2h = nn.Linear(input_size,hidden_size)
        self.h2o = nn.Linear(hidden_size,output_size)
        
    def forward(self,data,last_hidden):
        inputs = torch.cat((data,last_hidden),1)
        hidden = self.i2h(inputs)
        output = self.h2o(hidden)
        
        return hidden,output

        
    

In [32]:
rnn = RNN(50,20,10)

In [33]:
loss_fn = nn.MSELoss()

batch_size = 10
TIMESTEPS = 5
batch = Variable(torch.randn(batch_size, 50))
hidden = Variable(torch.zeros(batch_size, 20))
target = Variable(torch.zeros(batch_size, 10))

In [34]:
loss = 0 
for t in range(TIMESTEPS):
    hidden, output = rnn(batch,hidden)
    loss += loss_fn(output,target)
loss.backward()    

In [39]:
print(rnn.i2h.weight.grad.data)

tensor([[ 6.4866e-02, -7.4119e-02, -6.3060e-02,  ..., -3.4757e-02,
          1.0739e-02,  1.1959e-02],
        [ 5.9726e-02, -1.8990e-01,  1.5774e-02,  ..., -7.0121e-02,
          4.1341e-02, -2.1392e-03],
        [-8.9845e-02,  5.7795e-02, -8.4143e-02,  ...,  2.6410e-02,
         -1.3987e-02, -4.2004e-03],
        ...,
        [-2.5783e-02,  1.2292e-01,  2.9126e-02,  ...,  9.8170e-02,
         -7.4513e-03, -3.2644e-02],
        [ 1.2227e-02, -5.5118e-02, -8.5919e-02,  ..., -3.1665e-02,
          2.1021e-02,  9.3106e-03],
        [-4.6562e-02,  9.9821e-02, -4.4699e-03,  ...,  3.6211e-02,
         -4.0622e-02,  4.6574e-03]])


In [54]:
class MNISTConvNet(nn.Module):
    def __init__(self):
        super(MNISTConvNet,self).__init__()
        self.conv1 = nn.Conv2d(1, 10, 5)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(10, 20, 5)
        self.pool2 = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
        
    def forward(self,inputs):
        x = self.pool1(F.relu(self.conv1(inputs)))
        x = self.pool2(F.relu(self.conv2(x)))
        
        x = x.view(x.size(0),-1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return x

    
    

                
            

In [56]:
def printnorm(self,input,output):
        # input是将输入打包成的 tuple 的input
        # 输出是一个 Variable. output.data 是我们感兴趣的 Tensor
        print('Inside ' + self.__class__.__name__ + ' forward')
        print('')
        print('input: ', type(input))
        print('input[0]: ', type(input[0]))
        print('output: ', type(output))
        print('')
        print('input size:', input[0].size())
        print('output size:', output.data.size())
        print('output norm:', output.data.norm())    

        
def printgradnorm(self,grad_input,grad_output):
        print('Inside ' + self.__class__.__name__ + ' backward')
        print('Inside class:' + self.__class__.__name__)
        print('')
        print('grad_input: ', type(grad_input))
        print('grad_input[0]: ', type(grad_input[0]))
        print('grad_output: ', type(grad_output))
        print('grad_output[0]: ', type(grad_output[0]))
        print('')
        print('grad_input size:', grad_input[0].size())
        print('grad_output size:', grad_output[0].size())
        print('grad_input norm:', grad_input[0].data.norm())

In [57]:
net = MNISTConvNet()
net.conv2.register_forward_hook(printnorm)
print(net)

MNISTConvNet(
  (conv1): Conv2d(1, 10, kernel_size=(5, 5), stride=(1, 1))
  (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(10, 20, kernel_size=(5, 5), stride=(1, 1))
  (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=320, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=10, bias=True)
)


In [61]:
net.conv2.register_backward_hook(printgradnorm)
input = Variable(torch.randn(1, 1, 28, 28))
out = net(input)
print(out.size())

Inside Conv2d forward

input:  <class 'tuple'>
input[0]:  <class 'torch.Tensor'>
output:  <class 'torch.Tensor'>

input size: torch.Size([1, 10, 12, 12])
output size: torch.Size([1, 20, 8, 8])
output norm: tensor(14.8274)
torch.Size([1, 10])


In [62]:
target = Variable(torch.LongTensor([3]))
loss_fn = nn.CrossEntropyLoss()  # LogSoftmax + ClassNLL Loss
err = loss_fn(out, target)
err.backward()

Inside Conv2d backward
Inside class:Conv2d

grad_input:  <class 'tuple'>
grad_input[0]:  <class 'torch.Tensor'>
grad_output:  <class 'tuple'>
grad_output[0]:  <class 'torch.Tensor'>

grad_input size: torch.Size([1, 10, 12, 12])
grad_output size: torch.Size([1, 20, 8, 8])
grad_input norm: tensor(0.1266)
Inside Conv2d backward
Inside class:Conv2d

grad_input:  <class 'tuple'>
grad_input[0]:  <class 'torch.Tensor'>
grad_output:  <class 'tuple'>
grad_output[0]:  <class 'torch.Tensor'>

grad_input size: torch.Size([1, 10, 12, 12])
grad_output size: torch.Size([1, 20, 8, 8])
grad_input norm: tensor(0.1266)


In [49]:
print(err)

tensor(2.3118)


In [50]:
print(net.conv1.weight.grad.size())

torch.Size([10, 1, 5, 5])


In [51]:
print(net.conv1.weight.data.norm()) 

tensor(1.8076)


In [53]:
print(net.conv1.weight.data )

tensor([[[[ 0.0008, -0.0816,  0.0310,  0.1686, -0.0389],
          [-0.0050, -0.0788,  0.0251,  0.0109,  0.0434],
          [ 0.0835,  0.1897, -0.1687, -0.0181,  0.1255],
          [ 0.1062,  0.0422, -0.1908,  0.0672, -0.0682],
          [-0.0082, -0.1798,  0.0592,  0.0936,  0.1094]]],


        [[[ 0.1595, -0.1299,  0.1768, -0.1956,  0.1226],
          [ 0.0398,  0.0983, -0.0658,  0.0003,  0.1824],
          [ 0.0979,  0.1665,  0.1380,  0.0124,  0.0347],
          [-0.1168,  0.1872,  0.0698,  0.0945,  0.1028],
          [ 0.0536,  0.0379,  0.0934,  0.1520, -0.1947]]],


        [[[-0.0401, -0.0922, -0.0193,  0.0570,  0.1690],
          [ 0.1249, -0.1095, -0.1972, -0.0259, -0.0158],
          [-0.1746, -0.1906,  0.0617,  0.0348, -0.1981],
          [ 0.0776, -0.1885, -0.0495, -0.1041, -0.1412],
          [ 0.1412,  0.1706, -0.1284, -0.1279,  0.1303]]],


        [[[ 0.1859,  0.0130,  0.0675, -0.0208,  0.0736],
          [-0.0456, -0.1183,  0.1461, -0.1985, -0.0613],
          [ 0.0655,